version: '3'

services:
  app:
    image: tjfaccipieri/ec2integration:latest
    container_name: ec2integration
    restart: always
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production